spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
    date-format: 'yyyy-MM-dd HH:mm:ss'

  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 10485760
      max-file-size: 10485760
      enabled: true
logging:
  level:
    org.ck.teach.teachplatform: debug
debug: false


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.35.3:3306/ck_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  resources:
    static-locations: file:D://main/,classpath:/static/
  thymeleaf:
    cache: false
server:
  port: 801
#本地文件存储路径
staticFilePath: D://main/

---
spring:
  profiles: prod
  resources:
    static-locations: file:/tmp/,classpath:/static/
  datasource:
    url: jdbc:mysql://ck.keepon.top:3306/ck_db
  thymeleaf:
    cache: true
server:
  port: 80
#本地文件存储路径
staticFilePath: /tmp/



