
#本地文件存储路径
staticFilePath: D://main/

server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.35.3:3306/ck_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
    date-format: 'yyyy-MM-dd HH:mm:ss'
  thymeleaf:
    cache: false
  resources:
    static-locations: file:D://main/,classpath:/static/
#  servlet:
#    multipart:
      #单个最大  b
    #  max-file-size: 50
      #请求最大 b
    #  max-request-size: 100



logging:
  level:
    org.ck.teach.teachplatform: debug
debug: false







